-- ============================================================
-- 1. CREATE DATABASE
-- Creates a separate database for the Snowflake -> S3 export project
-- ============================================================

CREATE DATABASE SNOWFLAKE_S3_EXPORT_PRACTICE;


-- Selects the database for the remaining operations
USE DATABASE SNOWFLAKE_S3_EXPORT_PRACTICE;


-- ============================================================
-- 2. CREATE SCHEMA
-- Creates a schema to organize all project objects
-- ============================================================

CREATE SCHEMA S3_EXPORT_SCHEMA;


-- Selects the schema for the remaining operations
USE SCHEMA S3_EXPORT_SCHEMA;


-- ============================================================
-- 3. CREATE WAREHOUSE
-- Creates an XSMALL compute warehouse for this practice project
-- ============================================================

CREATE WAREHOUSE S3_EXPORT_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60       -- Suspends after 60 seconds of inactivity
    AUTO_RESUME = TRUE;     -- Automatically resumes when a query runs


-- Selects the warehouse used to execute queries
USE WAREHOUSE S3_EXPORT_WH;


-- ============================================================
-- 4. CREATE SOURCE TABLE
-- Creates the table containing the staff data to be exported
-- ============================================================

CREATE TABLE STAFF_DATA (
    STAFF_ID NUMBER,
    STAFF_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    CITY VARCHAR(100),
    SALARY NUMBER
);


-- Displays the table structure and column definitions
DESC TABLE STAFF_DATA;


-- ============================================================
-- 5. INSERT SAMPLE DATA
-- Inserts sample staff records into the source table
-- ============================================================

INSERT INTO STAFF_DATA
    (STAFF_ID, STAFF_NAME, DEPARTMENT, CITY, SALARY)
VALUES
    (201, 'Kshitij', 'Data Engineering', 'Pune', 1200000),
    (202, 'Rahul', 'AWS Engineering', 'Mumbai', 1000000),
    (203, 'Amit', 'Data Analytics', 'Bangalore', 900000),
    (204, 'Sneha', 'Data Engineering', 'Pune', 1100000),
    (205, 'Priya', 'Cloud Engineering', 'Hyderabad', 1050000);


-- Verifies the staff data inserted into the table
SELECT *
FROM STAFF_DATA;


-- ============================================================
-- 6. CREATE CSV FILE FORMAT
-- Defines how Snowflake should format the exported CSV file
-- ============================================================

CREATE FILE FORMAT STAFF_CSV_FORMAT
    TYPE = 'CSV'                        -- Export data in CSV format
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'  -- Encloses fields with double quotes when needed
    SKIP_HEADER = 1                     -- Skips the header when reading the file back
    COMPRESSION = 'NONE';               -- Does not compress the CSV file


-- Displays the available file formats
SHOW FILE FORMATS;


-- ============================================================
-- 7. CREATE STORAGE INTEGRATION
-- Creates a secure connection between Snowflake and Amazon S3
--
-- PREREQUISITE:
-- The AWS role SnowflakeS3ExportSnowflakeRole must already exist.
-- Paste its ARN into STORAGE_AWS_ROLE_ARN below.
--
-- No AWS access keys are stored in Snowflake - Snowflake assumes
-- the role through this integration instead.
-- ============================================================

CREATE OR REPLACE STORAGE INTEGRATION S3_EXPORT_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN =
        'arn:aws:iam::772346609795:role/SnowflakeS3ExportSnowflakeRole'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://snowflake-s3-export-practice-2026/employee-export/'
    );


-- ============================================================
-- 8. DESCRIBE STORAGE INTEGRATION
-- Shows the AWS IAM identity and external ID generated by Snowflake
--
-- Take STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID from
-- the output and paste them into the trust policy of the AWS role
-- SnowflakeS3ExportSnowflakeRole.
-- ============================================================

DESC INTEGRATION S3_EXPORT_INTEGRATION;


-- ============================================================
-- 9. CREATE EXTERNAL STAGE
-- Creates a Snowflake stage that points at the S3 location
-- ============================================================

CREATE OR REPLACE STAGE STAFF_S3_EXPORT_STAGE
    URL = 's3://snowflake-s3-export-practice-2026/employee-export/'
    STORAGE_INTEGRATION = S3_EXPORT_INTEGRATION
    FILE_FORMAT = STAFF_CSV_FORMAT;


-- Displays the available stages
SHOW STAGES;


-- Displays the configuration/details of the created stage
DESC STAGE STAFF_S3_EXPORT_STAGE;


-- ============================================================
-- 10. TEST S3 CONNECTIVITY
-- Lists the files currently present in the S3 prefix
--
-- "0 rows" is fine when nothing has been exported yet.
-- The important part is that you do NOT get "Access Denied".
-- ============================================================

LIST @STAFF_S3_EXPORT_STAGE;


-- ============================================================
-- 11. CREATE STORED PROCEDURE
-- Exports STAFF_DATA to S3 as ONE named CSV file
-- AWS Lambda will call this procedure
-- ============================================================

CREATE OR REPLACE PROCEDURE EXPORT_STAFF_TO_S3()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    -- Exports STAFF_DATA as ONE file named staff_data.csv in S3
    COPY INTO @STAFF_S3_EXPORT_STAGE/staff_data.csv
    FROM STAFF_DATA
    FILE_FORMAT = (
        FORMAT_NAME = 'STAFF_CSV_FORMAT'
    )
    HEADER = TRUE       -- Writes the column names as the first row
    SINGLE = TRUE       -- Creates ONE output file instead of many part files
    OVERWRITE = TRUE;   -- Replaces the file if it already exists

    -- Returns a success message to Lambda
    RETURN 'SUCCESS: Staff data successfully exported to S3 as staff_data.csv';

END;
$$;


-- ============================================================
-- 🚫 DO NOT RUN THE STATEMENT BELOW BY HAND
-- Who runs it : AWS Lambda — function snowflake-s3-export-lambda
-- Why         : Lambda is the thing that is supposed to start the export.
--               This procedure writes staff_data.csv to S3, so running the
--               CALL yourself will export the file outside the pipeline.
--               Later, when you press Test in Lambda, you can no longer tell
--               whether Lambda really did the work.
-- ============================================================

-- CALL EXPORT_STAFF_TO_S3();      <-- left commented out on purpose
-- Lambda runs it with: cursor.execute("CALL EXPORT_STAFF_TO_S3()")
