import os
import boto3

# ─── Configuration ────────────────────────────────────────────────────────────
REGION    = "us-east-1"
SENDER    = "kshitijjavir@outlook.com"

# Multiple recipients - as a list
RECIPIENTS = [
    "kshitijjavir110@gmail.com",
    "kshitijjavir111@gmail.com",
]

SUBJECT   = "AWS Lambda Notification - SES Trigger Successful"

# Path to email.html - same folder as this lambda_function.py
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "email.html")

ses = boto3.client("ses", region_name=REGION)


# ─── Helpers ──────────────────────────────────────────────────────────────────
def load_html_template() -> str:
    """Read email.html from the Lambda deployment package."""
    with open(TEMPLATE_PATH, "r", encoding="utf-8") as f:
        return f.read()


def build_text_fallback() -> str:
    """Plain-text fallback for email clients that block HTML."""
    return (
        "Hello,\n\n"
        "This is an automated notification confirming that your AWS Lambda "
        "function was triggered successfully and has dispatched this email "
        "through Amazon SES.\n\n"
        "STATUS: Lambda hit SES successfully\n\n"
        "EXECUTION DETAILS\n"
        "-----------------\n"
        "Lambda Function : test-ses-lambda\n"
        "AWS Region      : us-east-1 (N. Virginia)\n"
        "Service         : Amazon SES\n"
        "Trigger         : Manual Test Invocation\n\n"
        "No action is required. This message is sent for verification "
        "purposes only.\n\n"
        "--\n"
        "This is an automated email generated by AWS Lambda and delivered "
        "via Amazon SES.\n"
        "Please do not reply to this message.\n"
    )


# ─── Handler ──────────────────────────────────────────────────────────────────
def lambda_handler(event, context):
    try:
        html_body = load_html_template()
        text_body = build_text_fallback()

        response = ses.send_email(
            Source=SENDER,
            Destination={"ToAddresses": RECIPIENTS},
            Message={
                "Subject": {
                    "Data": SUBJECT,
                    "Charset": "UTF-8"
                },
                "Body": {
                    "Text": {
                        "Data": text_body,
                        "Charset": "UTF-8"
                    },
                    "Html": {
                        "Data": html_body,
                        "Charset": "UTF-8"
                    }
                }
            }
        )

        message_id = response["MessageId"]
        print(f"Email sent successfully! MessageId: {message_id}")

        return {
            "statusCode": 200,
            "body": f"Email sent! MessageId: {message_id}"
        }

    except Exception as e:
        print(f"Error sending email: {e}")
        raise
